### ISSUE TITLE
eslint v7 support

### ISSUE THREAD

**Issue by ljharb** [airbnb/javascript#2223]
Just like #2036, #1834, #1447, I'm filing this in advance.

eslint v7 was released on 5/8.

The current plan is, if possible, to release a new semver-minor of both configs, that `5 || 6 || 7`.

The timeframe for eslint v7 support is "probably not as soon as you would like, but as soon as we can".
Please accept this, and please add no noise to this thread beyond emoji reactions - distractions won't help anyone get the work done any faster.

### **Please** do not file additional issues and do not file pull requests attempting to add support - please, instead, continue to use eslint v6 until such time as our configs support v7.

Peer Dep eslint combined v5, v6, and v7 support released:
 - [x] [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import/issues/1772)
    - [x] [commit](https://github.com/benmosher/eslint-plugin-import/commit/6a110dd16a7fd775f08601054bf14ffd503eea7b)
    - [x] Release ([PR](https://github.com/benmosher/eslint-plugin-import/pull/1804))
 - [x] [`eslint-find-rules`](https://github.com/sarbbottam/eslint-find-rules/issues/318)
   - [x] [PR](https://github.com/sarbbottam/eslint-find-rules/pull/319)
   - [x] [Release](https://github.com/sarbbottam/eslint-find-rules/pull/321)
 - [x] update the base config
 - [x] publish the base config, semver-minor
 - [x] `eslint-plugin-react`
   - [x] [PR](https://github.com/yannickcr/eslint-plugin-react/pull/2635)
   - [x] [Release](https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.20.0)
 - [x] [`eslint-plugin-jsx-a11y`](https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/683)
   - [x] [PR](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/684) (blocked on ~base config~ and [jsx-ast-utils](https://github.com/jsx-eslint/jsx-ast-utils/pull/97))
   - [x] [Release](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/702)
 - [x] [`eslint-plugin-react-hooks`](https://github.com/facebook/react/issues/18876)
   - [x] [PR](https://github.com/facebook/react/pull/18878)
   - [x] [Release](https://github.com/facebook/react/commit/9f396bdd5d64be4ba02f0e74e12b686b626c3f1d)
 - [x] update the main config
 - [x] publish the main config, semver-minor

**Comment by ljharb** [comment]
eslint-config-airbnb-base v14.2.0 has been released.

**Comment by yoyo837** [comment]
Hello! Did you forget to release `eslint-config-airbnb`?

**Comment by ljharb** [comment]
@yoyo837 nope! did you read the checklist in the OP?

**Comment by yoyo837** [comment]
> @yoyo837 nope! did you read the checklist in the OP?

Sorry, got it now.

**Comment by sidntrivedi012** [comment]
@ljharb When will the airbnb-config be releasing with ESLint v7 support?

**Comment by ljharb** [comment]
`eslint-config-airbnb` v18.2.0 and `eslint-config-airbnb-base` v14.2.0 are now both released.
