### ISSUE TITLE
eslint v8 support

### ISSUE THREAD

**Issue by ljharb** [airbnb/javascript#2478]
(see also #2223, #2036, #1834, #1447)

eslint v8 was released on 10/9/21.

~The current plan is, if possible, to release a new semver-minor of both configs, that supports `5 || 6 || 7 || 8`.~ The plan is now to release a semver-major of both configs, that supports eslint 7 and 8 latest (at the time of publishing).

The timeframe for eslint v8 support is "probably not as soon as you would like, but as soon as we can".
Please accept this, and please add no noise to this thread beyond emoji reactions - distractions won't help anyone get the work done any faster.

### **Please** do not file additional issues and do not file pull requests attempting to add support - please, instead, continue to use eslint v7 until such time as our configs support v8.

Peer Dep eslint combined v7 and v8 support released:
 - [x] `eslint-plugin-import`
    - [x] [PR](https://github.com/import-js/eslint-plugin-import/pull/2191)
    - [x] [Release](https://github.com/import-js/eslint-plugin-import/releases/tag/v2.25.0)
 - [x] [`eslint-find-rules`](https://github.com/sarbbottam/eslint-find-rules/issues/336)
   - [x] [PR](https://github.com/sarbbottam/eslint-find-rules/pull/337)
   - [x] [Release](https://github.com/sarbbottam/eslint-find-rules/pull/341)
 - [x] update the base config
   - [x] [PR](https://github.com/airbnb/javascript/pull/2495)
 - [x] publish the base config, semver-major
 - [x] `eslint-plugin-react`
   - [x] `@babel/eslint-parser` supports eslint 8 ([PR](https://github.com/babel/babel/pull/13782))
   - [x] [PR](https://github.com/yannickcr/eslint-plugin-react/pull/3059) (blocked on base config and [eslint-find-rules](https://github.com/sarbbottam/eslint-find-rules/pull/337))
   - [x] Release
 - [x] [`eslint-plugin-jsx-a11y`](https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/683)
   - [x] [PR](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/810) (blocked on base config)
   - [x] Release
 - [x] [`eslint-plugin-react-hooks`](https://github.com/facebook/react/issues/22533)
   - [x] [PR](https://github.com/facebook/react/pull/22248)
   - [x] [Release](https://github.com/facebook/react/pull/22248#issuecomment-964176674)
 - [x] update the main config (blocked on [jsx-a11y bug](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/824))
    - [x] [PR](https://github.com/airbnb/javascript/pull/2498)
 - [x] publish the main config, semver-major

**Comment by dannyphillips** [comment]
Any update on this?

**Comment by ljharb** [comment]
v15.0.0 of the base config has now been released.

Remaining blockers for the react config include eslint-plugin-react, eslint-plugin-jsx-a11y, and eslint-plugin-react-hooks - the former two are likely unblocked by this release, which I'll explore in the coming days. The latter can only be resolved by a release from the react team; hopefully that happens before it's the lone obstacle.

**Comment by MichaelDeBoey** [comment]
`eslint-plugin-react-hooks@4.3.0` is published

https://github.com/facebook/react/pull/22248#issuecomment-964176674

**Comment by ljharb** [comment]
hey, look at that

**Comment by ljharb** [comment]
https://twitter.com/ljharb/status/1458540388185038851
